name: Build Vale Package

on:
  push:
    branches: [ main ]
  workflow_dispatch: # allow manual runs

jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6.0.2

      - name: Create Vale package zip
        run: |
          PACKAGE_DIR="pfe-vale"
          PACKAGE_NAME="pfe-vale.zip"

          mkdir "$PACKAGE_DIR"
          mv .vale.ini styles "$PACKAGE_DIR"/

          zip -r "$PACKAGE_NAME" "$PACKAGE_DIR"
          echo "PACKAGE_NAME=$PACKAGE_NAME" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Platform Engineering Vale Package (latest)
          files: ${{ env.PACKAGE_NAME }}
          make_latest: true 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
